### ISSUE TITLE
构建工具rollup数据要确认一下，添加单独的load page时间指标

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#129]

**Comment by ruleeeer** [comment]
https://github.com/originjs/js-bundler-benchmark/commit/f8beacab14b432e2b0e25b58fced72fda116ca18

**Comment by ruleeeer** [comment]
添加了单独的loadPage指标
<img width="1281" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/70385062/2917d87a-9b8e-4dec-a80e-f9dd1a76e6f6">
