### ISSUE TITLE
feat: 对比功能优化

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#139]

**Comment by Chieffo2021** [comment]
1. <img width="388" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/85914490/e35fb962-bda8-4c8c-9eae-ac995db5081f">
2. <img width="640" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/85914490/7d8f1188-a452-4c4b-b7a1-3485b17a0853">
3. 只展示差异
4. <img width="442" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/85914490/a30d553d-ae20-464f-901b-ff29fcc89ce5">

**Comment by Chieffo2021** [comment]
done
