### ISSUE TITLE
feat: compass 数据持续集成并补充组织相关数据

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#146]
第一期：重新集成compass数据，并增加自动集成接口
第二期：增加组织相关信息并集成

**Comment by muclover** [comment]
第一期补充数据
第二期增加组织相关信息

**Comment by muclover** [comment]
第一期完成，组织相关信息等compass的bug修复后再集成

**Comment by muclover** [comment]
第一期开始同步向compass提交pr增加项目信息

**Comment by muclover** [comment]
三大框架的数据已经补充完毕。
compass 接口有问题：
- 有重复数据
- 好像需要指定 beginDate 
解决后再重新集成一次数据

**Comment by wangsongc** [comment]
持续集成中

**Comment by flyfishzy** [comment]
考虑如下几种方案：
1. 集成COMPASS
2. 使用CHAOSS计算
3. 调用big querry数据计算

**Comment by muclover** [comment]
转向CHAOSS计算
