### ISSUE TITLE
对比界面部分npm周下载量显示为空

### ISSUE THREAD

**Issue by wangsongc** [originjs/oss-evaluation-service#165]
### Describe the bug

![image](https://github.com/originjs/oss-evaluation-service/assets/40830929/05920a26-51a6-42dc-87c5-3021ca657d62)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by flyfishzy** [comment]
https://github.com/originjs/oss-evaluation-service/pull/167 这个可能会有影响
