### ISSUE TITLE
对比添加无性能评测的软件时报错&图标显示异常

### ISSUE THREAD

**Issue by wangsongc** [originjs/oss-evaluation-service#189]
### Describe the bug

1、添加对比后，图标未显示
![image](https://github.com/originjs/oss-evaluation-service/assets/40830929/58521b36-ee20-4ed3-a644-7d88785cc642)
2、对比添加无性能评测的软件时报错
![image](https://github.com/originjs/oss-evaluation-service/assets/40830929/0b258053-06f6-4625-abec-bb08599204c7)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Chieffo2021** [comment]
done
