### ISSUE TITLE
无法搜索到软件tape

### ISSUE THREAD

**Issue by wangsongc** [originjs/oss-evaluation-service#198]
### Describe the bug

github url：https://github.com/ljharb/tape
技术栈表中有tape，在github_projects中没有
![image](https://github.com/originjs/oss-evaluation-service/assets/40830929/e4196ab2-a21c-4db4-9283-070c8e4828b7)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by llin6025** [comment]
软件是存在的，搜索服务内联了npm包和github关系表，当前数据源需要在补充包关系，现阶段建议把内联改成外联，缺少npm包数据的页面暂不展示
![image](https://github.com/originjs/oss-evaluation-service/assets/41422726/2bcc8ee7-c9a2-41bf-ac0f-76d10c8704c1)

**Comment by ruleeeer** [comment]
更改为外连接查询,没有npm包的软件不再报错,而是返回一个空的npm信息

**Comment by codejeffrey** [comment]
验证通过
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/65ce89d2-db22-43cd-942a-59fd3fce347f)
