### ISSUE TITLE
软件详情查看软件jest报错

### ISSUE THREAD

**Issue by wangsongc** [originjs/oss-evaluation-service#203]
### Describe the bug

Cannot read properties of null (reading 'commitFrequency')
![image](https://github.com/originjs/oss-evaluation-service/assets/40830929/17fe25ee-74e4-419e-b8d9-77643610f136)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Chieffo2021** [comment]
`project/activity` 接口返回了 null 数据
<img width="223" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/85914490/9bb2066f-95c6-4f02-b4c7-35eb5a1e10d0">
