### ISSUE TITLE
SonarCloud Scan增加报告链接

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#227]
### Description

可以跳转到报告详情

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by codejeffrey** [comment]
验证通过
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/cc41e1c7-76ea-4e38-a282-3e02aba7d7c5)
