### ISSUE TITLE
图标引用失效了

### ISSUE THREAD

**Issue by Chieffo2021** [originjs/oss-evaluation-service#250]
### Describe the bug

<img width="420" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/85914490/4db95c52-90bd-40f4-93b6-50afbc608d29">

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by codejeffrey** [comment]
验证通过
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/78a1ec09-6c1b-4d1c-9c4c-4abf8f0e9bf6)
