### ISSUE TITLE
项目生态对比缺少活跃度指标

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#252]
### Describe the bug

![image](https://github.com/originjs/oss-evaluation-service/assets/9528435/fc7eec82-dd25-4178-b73c-38ad2b289caf)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by codejeffrey** [comment]
验证ok
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/4489afc8-845d-45e2-8093-b69f26c3a3a3)
