### ISSUE TITLE
构建子技术栈Benchmark无结果的应该展示位N/A

### ISSUE THREAD

**Issue by jiawulin001** [originjs/oss-evaluation-service#254]
### Describe the bug

当构建子技术栈Benchmark无结果的接口返回的是-1，修改为N/A
![image](https://github.com/originjs/oss-evaluation-service/assets/14244944/39eb62d6-5157-4d8f-a827-fbe5b7b54f19)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Jiannan-dev** [comment]
两侧都已修改为--
