### ISSUE TITLE
OpenRank tips error in compare page

### ISSUE THREAD

**Issue by codejeffrey** [originjs/oss-evaluation-service#274]
### Describe the bug

OpenRank tips error in compare page
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/1289f860-3afd-4889-8a35-f129e9f73dd5)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by codejeffrey** [comment]
#275

**Comment by flyfishzy** [comment]
验证OK

**Comment by codejeffrey** [comment]
验证通过
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/247c2ea0-f368-4fbd-a109-daa474a00852)
