### ISSUE TITLE
功能分数计算结果是否正确

### ISSUE THREAD

**Issue by Chieffo2021** [originjs/oss-evaluation-service#302]
### Describe the bug

看结果和详情对比，至少solid和svelte是比react都高的。

![dc7e223c-0af9-4c8b-8859-52637f995a79](https://github.com/originjs/oss-evaluation-service/assets/85914490/88aaff01-7c67-4d03-b4d5-c122baabc23f)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by flyfishzy** [comment]
功能指标加入了代码量的维度，需要在比较页面功能维度体现出来
