### ISSUE TITLE
【最近版本发布数】数据确认

### ISSUE THREAD

**Issue by Chieffo2021** [originjs/oss-evaluation-service#306]
### Describe the bug

1. 最近指的是什么时间范围？建议加上tips解释
2. angular的最近发布数是107，数值是不正确？

![image](https://github.com/originjs/oss-evaluation-service/assets/85914490/93dcf210-66c4-4ad1-90de-50e829dfba8b)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by muclover** [comment]
解释：过去12个月版本发布的数量。

**Comment by muclover** [comment]
![image](https://github.com/originjs/oss-evaluation-service/assets/73372290/7d6c04ba-dd8c-49f3-8324-6ca9c738bfe1)
