### ISSUE TITLE
feat: 趋势榜单完善

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#354]
### Description
- **目标**
 通过趋势榜单识别出开源业界动向，挖掘出先进开源软件

- **手段**
1. 实现github趋势采集和展现，包括总榜、季度榜单、月度榜单等
2. 实现npm趋势采集和展现，包括总榜、季度榜单、月度榜单等
3. 先进性评估的评分Top榜单

- **可能的应用场景**
1. TMG按技术栈维度关注
2. 洞察月报中体现新兴的先进软件
3. 开源的使用者关注
### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Jiannan-dev** [comment]
提供一些趋势榜单的参考,目前来看还是oss-insight的更加全面
1. github趋势榜单  https://github.com/trending
2. bestofjs  https://bestofjs.org/
3. oss-insight https://ossinsight.io/collections
4. githunt,看起来和github trend类似  https://kamranahmed.info/githunt
5. 开发者维度的排名 https://githubrank.com/
6. [hellogithub.com](https://hellogithub.com/)

**Comment by Jiannan-dev** [comment]
# oss-insight
## oss-insight 的趋势榜单已经做了分类,分类榜单可以更轻松的找到自己关心的领域
<img width="1199" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/70385062/4d20c7e6-72df-4414-bb0b-5be150391e94">

## oss-insight提供了三种(star,pr,issue)维度的排名,以前端开发的视角来看,可能会关注refinedev/refine 是什么,为什么star上升较多,同样,一个库如果issue上升较快,是否可以代表可能问题较多
<img width="900" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/70385062/807cb71a-6bd9-4f34-bce3-8cba04244e4b">

## oss-insight已经提供了各种接口来获取趋势数据 https://ossinsight.io/docs/api/list-repos-of-collection

**Comment by Jiannan-dev** [comment]
大部分需要的指标已经在oss-insight提供了,这里提出一些oss-insight没有但是可能有意义的趋势类型:
1. tmg应该会很关心新的技术,例如web components,wasm 我们能否给出最近一个月新增的仓库中其中有多少是web components/wasm 的数据?
2. 能否给出rust软件在前端工具链的占比程度来体现rust在前端的影响力趋势?
3. 获取新增仓库的tag 来进行排名,得到最近较为流行或者上升明显的技术的趋势榜单?

**Comment by codejeffrey** [comment]
补充：https://open-leaderboard.x-lab.info/
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/b904cb9e-994e-4524-923e-ef4da58337cd)

1.根据 GitHub 所有仓库和开发者的行为计算项目、组织、开发者的活跃度并进行排名，可以看到上升下降趋势，使用一种算法计算OpenRank值
2.数据由OpenDigger提供，是否需要搭建环境才能获取数据？

**Comment by flyfishzy** [comment]
## libhunt
https://www.libhunt.com/
### 可根据语言筛选
![image](https://github.com/originjs/oss-evaluation-service/assets/9528435/84f3147e-1d19-4f51-897e-4ab9a25d917d)
### 社交平台的提及情况
![image](https://github.com/originjs/oss-evaluation-service/assets/9528435/ca3b4897-ca1c-4870-a760-99b3a3e94d8f)
### 热门topic & 最新发现的项目
![image](https://github.com/originjs/oss-evaluation-service/assets/9528435/3e304b29-b5e3-4b30-b97c-8ff8c021ab6b)

**Comment by flyfishzy** [comment]
## Github开源项目精选周刊
https://github.com/OpenGithubs/weekly
https://open.itc.cn/
- 日榜/周榜/月榜
- 精选周刊
![image](https://github.com/originjs/oss-evaluation-service/assets/9528435/047130d6-be0a-4f9e-9471-1443fd7f13d4)

入选ruanyf 周刊中的开源项目，是否也可以上榜？
https://github.com/ruanyf/weekly

**Comment by flyfishzy** [comment]
> 补充：https://open-leaderboard.x-lab.info/ 
> 
> 1.根据 GitHub 所有仓库和开发者的行为计算项目、组织、开发者的活跃度并进行排名，可以看到上升下降趋势，使用一种算法计算OpenRank值 2.数据由OpenDigger提供，是否需要搭建环境才能获取数据？

OpenDigger 已经爬取了数据，但我们没有存趋势的数据。
建议我们用自己的评估模型计算

**Comment by WilliamHeaven** [comment]
是否可以统计项目浏览量的排行，确定流行的项目，不过目前只有项目管理员，才能调用GitHub Api 获取信息。
接口文档：[链接](https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28)
```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/traffic/clones
```

**Comment by Jiannan-dev** [comment]
## 提交项目方式
### oss-insight
oss-insight的榜单分类功能实际上是用户操作的，需要用户提交一个文件到仓库中，文件内容类以下内容，用户可以借此只关注自己提交的分类软件，https://ossinsight.io/collections/open-source-database
<img width="330" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/70385062/bee15825-19bd-4315-8536-d914a22fbd2a">

**Comment by Jiannan-dev** [comment]
问题：
1、先进行评估分数的TOP榜单当前应该只有总榜，周/月/季度当榜单需要随时间刷新分数，当前能力尚不支持

**Comment by Jiannan-dev** [comment]
<img width="829" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/70385062/6dfa7fa7-bda8-444e-b8b1-3946c70b9591">

**Comment by Jiannan-dev** [comment]
补充
1、新兴类的软件最好能根据创建时间给出标签显示是新创建的项目
2、总榜数据也需要基线，提供给其他BU使用   -- 2024-8-13

**Comment by Jiannan-dev** [comment]
1、生态评分和质量评分的历史  -- 表结构和数量确定
2、判断下定时器是否能每月自动算出评分   表名称--oss_evaluation_summary
@TRebirthC

**Comment by TRebirthC** [comment]
> 1、生态评分和质量评分的历史 -- 表结构和数量确定 2、判断下定时器是否能每月自动算出评分 表名称--oss_evaluation_summary @TRebirthC

1、设置表oss_evaluate_summary_history以存储历史评分信息，表中具有主键id、唯一键project_id和date、评分信息（功能、质量、生态、创新评分）
2、已设置每月1日00:00自动计算评分并存储历史评分

**Comment by Jiannan-dev** [comment]
补充需求：
由于目前采集的是github_projects_t表的数据，但是如果有一些较新的项目不在该表中，会导致无法获取趋势榜单的历史数据，考虑从一下地址每天采集项目进入github_project_t中
1、oss-insight的趋势仓库  https://ossinsight.io/docs/api/list-trending-repos
2、oss-insight的ranking仓库 （star、pr、issue）https://ossinsight.io/docs/api/collection-repo-ranking-by-stars
3、oss-insight 的collection中包含的项目，这部分是人员手工标记的 https://ossinsight.io/docs/api/list-collections
4、github的 trend数据 (日周月） https://github.com/trending?since=daily&spoken_language_code=

**Comment by TRebirthC** [comment]
> 补充需求： 由于目前采集的是github_projects_t表的数据，但是如果有一些较新的项目不在该表中，会导致无法获取趋势榜单的历史数据，考虑从一下地址每天采集项目进入github_project_t中 1、oss-insight的趋势仓库 https://ossinsight.io/docs/api/list-trending-repos 2、oss-insight的ranking仓库 （star、pr、issue）https://ossinsight.io/docs/api/collection-repo-ranking-by-stars 3、oss-insight 的collection中包含的项目，这部分是人员手工标记的 https://ossinsight.io/docs/api/list-collections 4、github的 trend数据 (日周月） https://github.com/trending?since=daily&spoken_language_code=

oss趋势榜包括总榜和各集合榜单。请求oss各集合中包含的项目最多返回50个项目，请求oss各集合的ranking仓库最多返回1000个项目，其中star ranking是最完整的，故仅通过oss的star ranking来获取各集合的新兴项目。

最终用于集成的仓库有：

1. oss-insight的趋势仓库（每天0点集成）
2. oss-insight的star ranking仓库（每周一0点集成）
3. github的每日trend数据（每天0点集成）
4. github的每周、每月trend数据（每周一0点集成）

**Comment by Jiannan-dev** [comment]
2024-09-10 讨论
1、star一致性问题（历史、实时） #692 
2、github trend 趋势携带语言（主要使用常见的语言和内部的五大语言+all） @TRebirthC 
3、 软件如果进入了某一版趋势榜单，可以在github的项目上增加标签，例如[2024-01月榜单...]
4、由于月的时间线过长，增加周的数据采集（仅限star和contributor）@ruleeeer
5、趋势榜单接口增加项目创建时间列 @TRebirthC 
6、排名的数据进行基线，以提供历史性的查询，例如查看几个月之前的排名数据（只进行无筛选条件基线)@TRebirthC

**Comment by Jiannan-dev** [comment]
已上线初版，issue关闭
