### ISSUE TITLE
搜索软件返回数据不全

### ISSUE THREAD

**Issue by Chieffo2021** [originjs/oss-evaluation-service#357]
### Describe the bug

比如搜索 a，只返回了 9 条数据，建议前端增加滚动加载，后端增加翻页参数
<img width="1172" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/85914490/0c2a7d62-675f-474f-bb32-799f9e34da77">

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Jiannan-dev** [comment]
后端按照star数量排序返回10条数据，vuejs-router不在前10的范围内，所以没有返回，后端已修改返回20条数据
