### ISSUE TITLE
数据定时集成

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#361]
## 操作
**1.生产和本地环境的区分**：环境变量 process.env.ENVIRONMENT = 'develop'/'prod'
为了更好的配置定时相关信息和方便异常处理，在 `scheduler` 文件夹下有两个文件
- `config.js`：定时器配置
- `job.js`：定时器任务调度

步骤：
1. 首先在集成中间中增加一个函数 xxxTimer，比如compassTimer/projectCodeSizeTImer，该函数调用 syanAllProjectxxx 来进行所有软件的数据集成。
```js
export async function cncfDocumentScoreTimer(startIndex = 0) {
  try {
    logger.info('[Integration][Document Best Practice Score] Document Score Integration Job start');
    await syncAllProjectCncfDocumentScore({ startIndex });
    logger.info(
      '[Integration][Document Best Practice Score] Document Score Integration Integration Job Successful!',
    );
  } catch (err) {
    if (Object.prototype.hasOwnProperty.call(err, 'startIndex')) {
      // some error happened, restart after 10s
      const { error, startIndex } = err;
      logger.error(`Some error happened: ${error}`);
      logger.error('Retry, wait 10s restart');
      await sleep(10000);
      // restart
      await cncfDocumentScoreTimer(startIndex);
    } else {
      logger.error(`Some Unknown Error Happened: ${err}`);
    }
  }
}
```
2. 在配置文件 config.js 中加入配置，其中 name 指定为刚刚编写的 xxxTimer 函数，cronScheduleTimer 为集成的 cron 表达式，enabled 是为了区分生产和开发环境。
```js
  tasks: [
    {
      name: 'cncfDocumentScoreTimer',
      cronScheduleTime: '0 0 * * 1', // 周一 00:00
      enabled: true,
    },
    {
      name: 'compassTimer',
      cronScheduleTime: '0 0 * * 2', // 周二 00:00
      enabled: isProduction, // only start in production environment
    },
  ],
```
3. 在 job.js 中的taskFactory中增加一个属性 xxxTimer
```js
// Compass Integration Timer
const taskFactory = {
  // 新增任务，直接加入函数名称到这里
  cncfDocumentScoreTimer,
  compassTimer,
  xxxTimer,
  createTask: function (taskName) {
    if (!this[taskName]) {
      throw new Error(`Task ${taskName} not found`);
    }
    return this[taskName];
  },
}
```

---
### Description

现有集成通过前端调用接口来进行手动集成。
需求：将现有的集成进行自动化定时集成并部署。
### 定时集成模块
定时器，在使用 Cron 表达式约定好每个任务的集成时间后，在集成时间到达时就能够开始集成
> 尽管 JS 是单线程的，但可以利用事件循环/工作线程/子进程等方法来进行多任务的调度

### 单软件集成接口
单软件的所有数据的定时任务列表：
1. 集成Github项目基本信息 --> 周 --> 每周六00:00 --> 当前没有all的接口
2. ~~插入技术栈~~
3. 集成CNCF Document Score数据 --> 月 --> 1号 00:00 （预计集成时间：30个小时）--> done
5. 集成Github star趋势（from ossinsight ）--> 月 --> 3号 00:00 --> syncAllProjectStargazersTrend
6. openrank数据 --> 周 --> 每周日 00:00 --> syncAllProjectOpendigger
7.  代码量  --> 月 --> 5号 00:00 -->done
8. 贡献者数量 --> 月  --> 7号 00:00 --> done
9. 依赖数量 --> 月 --> 9号 00:00 -->done
10. critical score --> 月 --> 11号 00:00 --> 无all接口，用单接口写
11. scorecard --> 月 --> 13号 00:00 --> 无all接口，用单接口写
12. 判断软件类型：JS、Rust、Java 等  --> 每周集成 
    1. 前端：npm相关数据
        1. 插入主包信息
        2. 包下载量 --> 周三 00:00 -->done
        3. 包大小  --> 周五 00:00 --> syncAllProjectPackageSize
13. compass数据  --> 月 --> 15号 00:00 --> done
14. sonarCloud数据 --> 手动
15. GitHub依赖软件数据  --> 月 --> 20号 00:00 --> syncAllProjectDependencies
16. ossinsight地理/组织数据  --> 月 --> 25号 00:00 --> syncAllProjectCreatorsCountries、syncAllProjectCreatorsOrg
17. 算分  --> 天？--> 每天 00:00 --> syncAllProjectEvaluation
18. 相似软件？ --> 暂无
**策略：**
- 没有all接口的，写一个接口，来通过单接口来获取所有的数据，然后走 all 接口的处理（也可以直接写到 Timer 中）
- 有 all 接口的，写一个 xxxTimer 接口，来进行调用。
- sonarCloud？

**相关问题**
- 技术栈相关数据
- 软件类型：从前端软件延伸到通用软件时必须要考虑的内容
- 前端软件需要插入主包数据后才能集成
- compass数据需要先提PR后才有相关数据，但已经有的软件数据可以增量更新
- sonarCloud接口暂无

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by muclover** [comment]
定时集成逻辑：
方案一：单个模块自己定义定时集成任务函数，然后在集成模块里进行统一进行调用返回定时器实例，然后再判断本地和生产环境，之后再调用定时任务。
- 接口参数：时间

方案二：统一在定时模块里定义定时集成任务，并调用

生产和本地环境的区分：环境变量
- `process.env.ENVIRONMENT = 'develop'/'prod'`

**Comment by Joker-john** [comment]
### 定时器相关模块现有信息
1、Github基本信息，每周六跑一遍（Token够不够，或者说会不会IP地址限速）
2、Github start 趋势，改接口（需要从Rest接口，改到直接读取页面的数据，这样不会限流）
3、openrank 每周
4、每个月刷一次代码量、贡献者数量、依赖数量
5、critical score  --> 手工？何昊
6、scorecard --> 何昊，找一下有无linux执行文件。月度（线上+本地），每个月本地跑
7、包下载量 --> 每周 
8、包大小 --> 2个月度
9、sonarCloud --> 手动，不用更新
10、GitHub依赖软件数据 -> 限流，爬虫，月度
12、算分，每周算一次
13、ossinsight地理/组织数据 --> 月度
保证在月底的时候，所有数据都跑了一遍。

**Comment by muclover** [comment]
**安排时间**
![image](https://github.com/user-attachments/assets/46761fb2-e11d-4ece-a602-9af80cd94944)
