### ISSUE TITLE
数据集成：增加单个软件的集成，将现有集成接口整合，能够快速补充某个软件的相关数据

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#367]
Todo：
- [ ] 补充根据数据库数据进行批量集成的接口和api（默认SQL为全量数据）
- [ ] 补充新的数据集成的单接口（scorecard、SonarCloud数据、依赖图数据、组织多样性/贡献者多样性数据）

**修改的时候只需要看这一段，不需要看下面的评论**
### 必选
- syncSingleProjectxxx(project,options)
  - 同步单个项目的某指标数据
  - eg: `syncSingleProjectCompassMetric()`
  - 参数：project 是GithubProjects对象
- syncAllProjectCompassMetric(options) 
  - 同步所有项目的某指标数据
  - eg: `syncAllProjectCompassMetric(options)`
### 可选
swagger调试接口API
- syncSingleProjectxxxHandler(req, res)
- syncAllProjectxxxHandler(req, res)

更详细的信息如下
# Description

现在的数据集成，涉及到许多接口，若需要临时补充或者重新集成单个数据，则需要调多个接口。
整合现有接口，提供一个对外的接口来补充数据

#### 统一现有接口的命名规范、参数约定、注释、异常处理等信息
在TypeScript的编程范式中，Options模式是一种常见做法，特别是在需要**提供多个配置项但又不想定义很多参数**的情况下。在下述例子中，4个参数可以不需要都提供，只需要传入一个部分匹配的参数对象即可。
```ts
interface ServerOptions {
  port: number;
  host?: string;
  logging?: boolean;
  timeout?: number;
}
function createServer(options: ServerOptions) {
    // 核心逻辑
}
createServer({port: 8088});
```
- 函数可以不需要注释，因为在 ServerOptions 对象的属性相当于注释。

但是，在 JS 中没有 interface，因此，我们采用约定的方式来进行处理，既方便数据集成的整合调用，也方便于后续的定时集成任务。

1. 对 router 的改造：约定所有 router 方法的命名为 **syncSingleProjectxxxHandler(req, res)**，其中 xxx 为集成命名
2. 对现有集成方法的命名约定和改造
    - 单项目集成：**syncSingleProjectxxx**，其中 xxx 为集成命名，例子：syncSingleProjectCompassMetric
    - 全量集成：**syncAllProjectxxx**，例子：syncAllProjectCompassMetric
3. 接口参数约定：对于单项目集成，约定一个公共参数 `project` 和一个可选参数 `options`
- 公共参数 project 通过 `utils.js` 中的方法 `getProjectByUrl` 获取：`const project = await getProjectByUrl(url);`
- 可选参数 options 自己根据需要使用，但需要在注释中写明(因为不像是TS有interface，所以显示在注释写出来，也方便后续转换为 TS)
```js
// 注释的方法一
/*
 * @params {{owner: string, name: string, age: number}} 
*/
// 注释的方法二
/*
 * @param {Object} options
 * @param {string} [options.beginDate]  integrate  begin date
 * @param {string} [options.endDate] integrate end date
 */
```

代码实例
```js
// 实例
export async function syncSingleProjectCompassMetricHandler(req, res) {
  // HTTP 请求的处理逻辑
}

/**
 * Synchronize Single Project Compass Metric
 * @param {Object} project project info
 * @param {Object} options
 * @param {string} [options.beginDate] - compass integrate date
 * @returns {Promise<*>} inserted compass metrics
 */
export async function syncSingleProjectCompassMetric(project, options) {
   // 核心集成处理逻辑
}
```
5. 定时器：定时器都需要写到新增的 `schedule_job.js` 文件中。并且需要定义自己的定时任务，后续再统一调用。在统一处理前需要考虑几个问题：
    1. 定时集成的增量集成，需要保持数据为最新的状态
    2. 定时集成的日志和错误处理，根据现有的集成模块，自定义不同的错误类型 Error，并根据错误类型来进行重试。
    3. 重试需要考虑，重试次数，日志处理以及人工介入的问题。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by muclover** [comment]
**更新：这个由各自接口负责人来解决，但都需要有更新/增量的集成策略**

**需要约定当 metadata 不存在时的处理行为**
现有接口的逻辑如下：
- opendigger的数据：集成的时候：若为空，则插入空数据？
- scorecard：若为空，则直接返回，不插入
- criticalityScore：若为空，则直接返回，不插入

**Comment by muclover** [comment]
背景：在 Express 中，路由处理器设计为直接响应 HTTP 请求，每个处理器关注于如何处理特定的请求路径和方法。虽然技术上可以在一个路由处理器中调用另一个，但这种做法并不推荐，原因包括但不限于以下几点：
1. 违反关注点分离（Separation of Concerns）：路由处理器应该只关注于处理对应的 HTTP 请求。混用将使得维护和理解代码变得更加困难。应该抽象出公共的接口模块。
2. 增加复杂性和维护成本：增加了代码的耦合度。当逻辑变化时，你可能需要更新多个地方的代码，这增加了维护成本
3. 破坏了中间件模型：Express 的路由系统和中间件模型是设计来按顺序处理请求的。如果你在路由处理器之间进行调用，可能会破坏这种逻辑流，并绕过了 Express 提供的中间件处理机制，如安全机制、日志等。
4. 难以跟踪和调试：跟踪请求经过的路径和处理逻辑会越来越难管理，特别是对于新增单个软件的情况，涉及到所有的数据集成模块以及一些新增逻辑。
5. 测试难度：单个路由的测试成本增加，依赖关系变得更加复杂

结论：**接口需要统一形式，JS没有接口，所以采用约定的方式来进行，如下**
1. api-doc 里面调用路由函数，路由函数调用响应的xxHandler
    - 参数：req, res
    - 具体的参数，通过 swagger 来定义
    - 在api-doc里直接调用
2. 单独的集成模块，除了xxhandle函数外，统一约定一个接口 xx，传入参数为
    - 约定参数：项目的唯一键，repoUrl
        - 确定是否都是 github 项目？如果是的话就使用仓库地址作为统一入参
    - 其他参数：自己定义
    - 功能：需要约定当数据不存在时的处理逻辑
        0. **基本处理逻辑**：数据未集成时，创建该数据，数据已集成，则 update **增量更新**（新增项目时，应该都是未集成的逻辑，此处需要考虑该接口中间出错时后，进行重复调用补充出错处的数据，且增量更新和一些基本的容错一般来说是必须考虑的），接下来考虑两个原始的 metadata 不存在时的处理逻辑：
        1. 不存在，则不执行，打印日志后，直接返回
        2. 不存在，则创建一条记录，但响应的数据位置为 null/空；
6. 单软件集成接口 syncNewProject：统一调用 xx
    - 参数：仓库地址 repoUrl
    - 调用其他接口的 xx，在总接口里面处理数据后传入相关信息即可
7. 数据自动化集成接口：
    - 需要定义 integration 接口，统一定义在原始文件中，然后调用 xx 完成数据的集成
    - 需要定义定时器模块，统一定义在 timer.js 文件中，调用相应的 integration 接口来集成
    - 然后在 timer.js 中，定义时间来约定不同数据的执行顺序、更新频率

**Comment by muclover** [comment]
每个模块的函数都接收两个参数：一个是公共参数project，另一个是一个包含所有其它参数的参数对象 options。

函数命名约定：
```js
//集成处理函数
syncSingleProjectCompassMetric(){} 
或者 integrateCompassMetricForSingleProject(){} 
或者 singleProjectCompassIntegration(){}
syncAllProjectCompassMetric(){} 
或者 integrateCompassMetricForAllProject(){} 
或者 allProjectCompassIntegration(){}

//定时任务
scheduleCompassMetric(){}
```

示例代码：
```js
// xxIntegrating.js
// 具体的数据集成函数，主要的集成逻辑入口
export async function xxIntegrating(project, options) {
   let { startDate, endDate} = options;
   // 集成逻辑
}
// 路由接口的处理函数入口
export async function xxIntegratingHandler(req, res) {
    const {repoUrl, startDate, endDate} = req.body;
    const project = await xxx.select({where: {html: repoUrl}})//查询project
    await xxIntegrating(project, {startDate, endDate).catch(e => { res.status(500).send(' integrating error'); });

    res.status(200).send('integrating success');
}
```

利用 options 来统一所有函数的入口参数，需要在接口文档中进行说明

在 Typescript 中，Options 是一组可配置的参数。可以作为接口参数的约定，这里想达到类似的效果，但 options 中具体有哪些参数和具体的类型，是自由的。不同接口为了方便可以定义属于自己的接口。

**Comment by muclover** [comment]
**不需要抽象，简单化，但是需要按照上述约定好接口、参数、命名**
问题点：如果使用模块化，在现有的 controller 基础上，是否需要抽离出 Service 层？
1. 抽离出 Service 层
2. 不抽离，但是在 controller 上做同样的事情，分离两种类型的接口，一类是基本的处理逻辑，另一类是为了响应 http 请求时的操作

**Comment by muclover** [comment]
两个 util 函数：
解析 github 仓库，可能不是必须的，因为在 github 项目表中也有相关数据
```js
function parseRepoUrl(repoUrl) {
  repoUrl = 'https://github.com/williamtroup/Journey.js';
  const regex = /^(https?:)\/\/(github\.com)\/([^\/]+)\/([^\/]+)$/;
  const match = repoUrl.match(regex);
  if (match) {
    return {
      protocol: match[1], // "https://"
      address: match[2], //github.com
      owner: match[3], // 用户名或组织名
      repository: match[4], // 仓库名
    };
  } else {
    // 如果不匹配，则抛出错误
    throw new Error('URL不是一个有效的GitHub主仓库地址');
  }
}
```

集成都需要的项目信息，除了 github 项目表外，其他都可以使用
```js
/**
 *
 * @param repoUrl github project url
 * @returns {Promise<*>} project basic information
 */
async function getProjectByUrl(repoUrl) {
  const project = await GithubProjects.findOne({
    attributes: ['id', 'htmlUrl'],
    where: {
      htmlUrl: repoUrl,
    },
  });
  if (project === null) {
    debug.log('project not exists');
    return;
  }
  return project;
}
```

**Comment by flyfishzy** [comment]
## 接口约定
### 必选
- syncSingleProjectXxx(project,options)
  - 同步单个项目的某指标数据
  - eg: `syncSingleProjectCompassMetric()`
  - 参数：project 是GithubProjects对象
- syncAllProjectXxx(options) 
  - 同步所有项目的某指标数据
  - eg: `syncAllProjectCompassMetric(options)`
### 可选
swagger调试接口API
- syncSingleProjectxxxHandler(req, res)
- syncAllProjectxxxHandler(req, res)
