### ISSUE TITLE
npm周下载量数据存在，但界面显示为0

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#405]
### Describe the bug

![image](https://github.com/originjs/oss-evaluation-service/assets/73372290/5aec6ab4-0695-4842-bedc-87c5e1bdae32)
![image](https://github.com/originjs/oss-evaluation-service/assets/73372290/e1d81475-a92b-49b0-9450-0004cd7eb3eb)

### Validations

- [x] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by codejeffrey** [comment]
前端做了数据处理除以1000，最终展示为0

**Comment by flyfishzy** [comment]
建议参考github的处理方式
![image](https://github.com/originjs/oss-evaluation-service/assets/9528435/c306a2c6-55d7-4097-ae94-627048c567b5)

**Comment by muclover** [comment]
## 统一整个页面的展示信息

1. 看是否大于1000，若小于，则暂时真实数据；如，392
2. 看是否>1000，则保留2位小数，如2.13k，23.31k
3. 看是否大于100k，则只保留整数部分，如 100k，245k

**Comment by flyfishzy** [comment]
https://github.com/originjs/oss-evaluation-service/issues/101

**Comment by codejeffrey** [comment]
保留2位小数，这些字段需要统一一下
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/2a16682c-45d5-4810-8270-34eef1cf38b1)
![image](https://github.com/originjs/oss-evaluation-service/assets/47146159/57aacf79-addc-4321-91c9-fa3334d78e3d)
