### ISSUE TITLE
软件详情echarts图表切换时渲染慢

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#417]
### Describe the bug

echarts图表长时间没有渲染出来，显示空白
![image](https://github.com/originjs/oss-evaluation-service/assets/9528435/297b78cf-f709-40ff-8abf-980aa738f974)

### Steps to reproduce

1. 打开软件详情页面。
2. 切换到其他chrome 网页
3. 再切换回软件详情页面
4. echarts图表会出现长时间没有渲染出来的情况

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Chieffo2021** [comment]
未复现
