### ISSUE TITLE
对巴士系数的解释

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#516]
### Describe the bug

明显sequelize贡献者更多，但巴士系数很低
![image](https://github.com/originjs/oss-evaluation-service/assets/73372290/c2aa177a-7f70-45e6-9f5c-ebecd4944b76)

### Validations

- [ ] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by flyfishzy** [comment]
open-digger的巴士系数有时间的属性，最新的查询结果是2024年
- https://oss.x-lab.info/open_digger/github/sequelize/sequelize/bus_factor.json
- https://oss.x-lab.info/open_digger/github/prisma/prisma/bus_factor.json

prisma的巴士系数看起来确实偏大，CHAOSS定义的[bus factor](https://chaoss.community/kb/metric-bus-factor/)指出结果取决于计算巴士系数的**贡献类型**（代码/翻译/文档/issue等都算贡献，但一般使用git提交）。

open-digger计算代码中采用的贡献类型是activity（'IssuesEvent', 'IssueCommentEvent', 'PullRequestEvent', 'PullRequestReviewCommentEvent' 这几种事件都包含在内），也就是说issue和pr代码贡献者都会算到巴士系数里。

- **总结**
修改巴士系数的提示信息，添加issue的内容，以免引起误解。
