### ISSUE TITLE
代码量计算有问题

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#562]
### Describe the bug

![image](https://github.com/originjs/oss-evaluation-service/assets/73372290/d7036897-95c7-4d01-bc33-3b74b70c6336)

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Jiannan-dev** [comment]
超大仓库使用本地计算
<img width="630" alt="image" src="https://github.com/originjs/oss-evaluation-service/assets/70385062/59f55bb6-738d-4ad4-8b97-2f53740256fc">
