### ISSUE TITLE
集成常见语言的github star > 5000的项目

### ISSUE THREAD

**Issue by Jiannan-dev** [originjs/oss-evaluation-service#568]
### Description

目前已完成以下语言集成
JavaScript
TypeScript
Python
Java
Go
C
C++
Rust

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Jiannan-dev** [comment]
待进行筛选\不合适软件去除\跑数据

**Comment by ygj6** [comment]
建议可以排除的：
- 已归档项目
- 涉及敏感信息的
- 学习资源类仓库尽量排除

**Comment by Jiannan-dev** [comment]
已经集成完毕，关闭
