### ISSUE TITLE
C/C++ 的 JSON 软件的 benchmark 对比

### ISSUE THREAD

**Issue by muclover** [originjs/oss-evaluation-service#584]
### Description

1. 对现有的 JSON 软件进行性能对比，利用 https://github.com/miloyip/nativejson-benchmark
2. 将对比数据导入到数据库

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by flyfishzy** [comment]
下一步：
- 补充一些json库参与评测
  - https://github.com/boostorg/json （性能对比：https://230.jsondocs.prtest.cppalliance.org/libs/json/doc/html/json/benchmarks.html）
  - https://github.com/simplejson/simplejson
  - https://github.com/json-parser/json-parser
  
rust版本是否也参与评测？
- https://github.com/serde-rs/json
- https://github.com/serde-rs/json-benchmark

**Comment by muclover** [comment]
https://github.com/hjiang/jsonxx.git 归档了，3年前更新，
https://github.com/simdjson/simdjson 上周，18.8k
https://github.com/boazsegev/facil.io.git 3个月前，2.1k
https://github.com/Microsoft/cpprestsdk.git 7个月前，7.8k

https://github.com/boostorg/boost.git 1
https://github.com/DaveGamble/cJSON.git 2周前，10.3k，1
https://github.com/rustyrussell/ccan.git 每周，1.1k，1
https://github.com/zserge/jsmn.git 3年前，3.6k，1
https://github.com/bblanchon/ArduinoJson.git 昨天更新，6.6k，1
https://github.com/nlohmann/json.git 3个月前，41.3k，1
https://github.com/kgabis/parson.git 9个月前，1.3k，1
https://github.com/json-c/json-c.git 2个月前，2.9k，1
https://github.com/dropbox/json11.git 归档，2.5k，4年前，1
https://github.com/udp/json-parser.git 3个月前更新，1.3k，1
https://github.com/akheron/jansson.git 4个月前更新，3k，1
https://github.com/kazuho/picojson.git 1年前更新，8k，1
https://github.com/miloyip/rapidjson.git 在更新，14k，1
https://github.com/lloyd/yajl.git 9年前更新，2.1k，1
https://github.com/open-source-parsers/jsoncpp.git 1年前，8k，1

**Comment by flyfishzy** [comment]
优先补充性能测试的：
- [simdjson](https://github.com/simdjson/simdjson)
- [serde-rs/json](https://github.com/serde-rs/json)

**Comment by flyfishzy** [comment]
补充这些json库的新版本测试 https://github.com/originjs/nativejson-benchmark
