### ISSUE TITLE
用户旅程梳理

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#626]
### Description

1. 用户搜索软件，如果在先进性搜索不到，会申请先进性评估
  a) 在首页或搜索结果中提供申请评估按钮
  b) 当前看不到申请的进展，需要提供进展查询，先进性爬取完数据后能通知到用户
2. 当能查到软件后，打开项目详情，查看相似软件
  a) 需要结合当前用户及领域landscape的技术栈分类，优先推荐同类技术栈软件 
  b) 可考虑结合AI提供软件功能的总结摘要
3. 添加到相似软件对比，对比界面性能指标能展开对比
4. 没有性能benchmark数据的软件，提供反馈benchmark数据入口
5. 对比后用户可导出先进性评估报告

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by flyfishzy** [comment]
benchmark改进
- 软件详情中性能指标没有也显示出来
- 添加`新增Benchmark`按钮入口
- 性能benchmark界面，`增加benchmark软件`改为`新增Benchmark`，内容包括
  - 上传excel
  - 测试环境信息：提示示例文字`The benchmark was run on GitHub-hosted runners(16 GB RAM, 4 Cores, ubuntu-22.04).`
  - 申请人信息
  - 下载模板的链接

**Comment by flyfishzy** [comment]
补充：性能benchmark界面，可以支持导出已有的benchmark数据

**Comment by Jiannan-dev** [comment]
benchmar 带技术栈导出已完成，导入待benchmark 整改后进行
