### ISSUE TITLE
部分软件待补充数据

### ISSUE THREAD

**Issue by flyfishzy** [originjs/oss-evaluation-service#636]
### Describe the bug

- salvoravida/redux-first-history
  - 缺少sonarcloud
  - 缺少COMPASS
- framer/motion
  - 缺少sonarcloud
- sudodoki/copy-to-clipboard
  - 缺少sonarcloud
  - 缺少COMPASS
- atlassian/pragmatic-drag-and-drop
  - 都缺少
- jobrunr/jobrunr
  - 缺少COMPASS
- bndtools/bnd
  - 缺少sonarcloud
  - 缺少COMPASS
- eclipse-equinox/equinox
  - 缺少COMPASS
- 

### Validations

- [ ] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by codejeffrey** [comment]
1

**Comment by Jiannan-dev** [comment]
sonar 除bndtools/bnd 外均已集成，bndtools/bnd本地编译失败，github fork方式同样失败

**Comment by codejeffrey** [comment]
COMPASS数据补充完成
