### ISSUE TITLE
仓库neovim/neovim没有集成到Github Star 趋势数据

### ISSUE THREAD

**Issue by WilliamHeaven** [originjs/oss-evaluation-service#655]
### Describe the bug

仓库neovim/neovim没有集成到Github Star 趋势数据
![image](https://github.com/user-attachments/assets/c8c8fde7-7323-41a7-8750-67b9f4ea91bb)

### Validations

- [ ] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by codejeffrey** [comment]
已补充，待下次数据同步，页面将会展示
