### ISSUE TITLE
调用汇总接口`/sync/syncSingleProjectAllMetadata`未集成到代码量

### ISSUE THREAD

**Issue by wangsongc** [originjs/oss-evaluation-service#673]
### Describe the bug

调用汇总接口`/sync/syncSingleProjectAllMetadata`未集成到代码量

### Validations

- [ ] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Jiannan-dev** [comment]
<img width="581" alt="图片" src="https://github.com/user-attachments/assets/262bb046-ddfc-403a-a485-5c99ec664de7">

获取代码量时会根据仓库大小判断是使用api还是clone后执行cloc，原本的集成接口没有查询size字段，导致没有走api接口查询
